name: perimeter-aws-typescript-infra-new
description: periemter aws typescript infra new
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: aws-typescript
